import SGML

enum AttributeKeys: String {
    case action
    case accesskey
    case alt
    case autocomplete
    case autocapitalize
    case autocorrect
    case autofocus
    case autoplay
    case blocking
    case checked
    case cite
    case `class`
    case closedby
    case colspan
    case content
    case contenteditable
    case controls
    case coords
    case crossorigin
    case data
    case datetime
    case dir
    case disabled
    case draggable
    case download
    case enctype
    case enterkeyhint
    case fetchpriority
    case `for`
    case form
    case formaction
    case formenctype
    case formmethod
    case formtarget
    case headingoffset
    case headingreset
    case height
    case hidden
    case httpEquiv = "http-equiv"
    case href
    case hreflang
    case id
    case inert
    case inputmode
    case integrity
    case `is`
    case itemid
    case itemprop
    case itemref
    case itemscope
    case itemtype
    case label
    case lang
    case loading
    case loop
    case media
    case method
    case multiple
    case muted
    case name
    case nonce
    case `open`
    case onerror
    case onload
    case onresize
    case onblur
    case onchange
    case oncontextmenu
    case onfocus
    case oninput
    case oninvalid
    case onreset
    case onsearch
    case onselect
    case onsubmit
    case onkeydown
    case onkeypress
    case onkeyup
    case onclick
    case ondblclick
    case onmousedown
    case onmousemove
    case onmouseout
    case onmouseover
    case onmouseup
    case onwheel
    case ondrag
    case ondragend
    case ondragenter
    case ondragleave
    case ondragover
    case ondragstart
    case ondrop
    case onscroll
    case oncopy
    case oncut
    case onpaste
    case onabort
    case oncanplay
    case oncanplaythrough
    case oncuechange
    case ondurationchange
    case onemptied
    case onended
    case onloadeddata
    case onloadedmetadata
    case onloadstart
    case onpause
    case onplay
    case onplaying
    case onprogress
    case onratechange
    case onseeked
    case onseeking
    case onstalled
    case onsuspend
    case ontimeupdate
    case onvolumechange
    case onwaiting
    case ontoggle
    case onafterprint
    case onbeforeprint
    case onbeforeunload
    case onbeforeinput
    case onmouseenter
    case onmouseleave
    case onselectionchange
    case onselectstart
    case onpointercancel
    case onpointerdown
    case onpointerenter
    case onpointerleave
    case onpointermove
    case onpointerout
    case onpointerover
    case onpointerup
    case ongotpointercapture
    case onlostpointercapture
    case onhashchange
    case onlanguagechange
    case onmessage
    case onmessageerror
    case onoffline
    case ononline
    case onpagehide
    case onpagereveal
    case onpageshow
    case onpageswap
    case onpopstate
    case onrejectionhandled
    case onstorage
    case onunhandledrejection
    case onunload
    case ping
    case placeholder
    case popover
    case preload
    case readonly
    case referrerpolicy
    case rel
    case required
    case rowspan
    case scope
    case shape
    case size
    case sizes
    case slot
    case span
    case spellcheck
    case src
    case srcset
    case style
    case tabindex
    case target
    case title
    case translate
    case type
    case typemustmatch
    case usemap
    case value
    case width
    case writingsuggestions
}


