import SGML

enum EventAttributeKey: String, AttributeKeyRepresentable {
    case onabort
    case onafterprint
    case onbeforeinput
    case onbeforeprint
    case onbeforeunload
    case onblur
    case oncanplay
    case oncanplaythrough
    case onchange
    case onclick
    case oncontextmenu
    case oncopy
    case oncuechange
    case oncut
    case ondblclick
    case ondrag
    case ondragend
    case ondragenter
    case ondragleave
    case ondragover
    case ondragstart
    case ondrop
    case ondurationchange
    case onemptied
    case onended
    case onerror
    case onfocus
    case ongotpointercapture
    case onhashchange
    case oninput
    case oninvalid
    case onkeydown
    case onkeypress
    case onkeyup
    case onlanguagechange
    case onload
    case onloadeddata
    case onloadedmetadata
    case onloadstart
    case onlostpointercapture
    case onmessage
    case onmessageerror
    case onmousedown
    case onmouseenter
    case onmouseleave
    case onmousemove
    case onmouseout
    case onmouseover
    case onmouseup
    case onoffline
    case ononline
    case onpagehide
    case onpagereveal
    case onpageshow
    case onpageswap
    case onpaste
    case onpause
    case onplay
    case onplaying
    case onpointercancel
    case onpointerdown
    case onpointerenter
    case onpointerleave
    case onpointermove
    case onpointerout
    case onpointerover
    case onpointerup
    case onpopstate
    case onprogress
    case onratechange
    case onrejectionhandled
    case onreset
    case onresize
    case onscroll
    case onsearch
    case onseeked
    case onseeking
    case onselect
    case onselectionchange
    case onselectstart
    case onstalled
    case onstorage
    case onsubmit
    case onsuspend
    case ontimeupdate
    case ontoggle
    case onunhandledrejection
    case onunload
    case onvolumechange
    case onwaiting
    case onwheel
}
