import SGML

enum StandardAttributeKey: String, AttributeKeyRepresentable {
    case accept
    case abbr
    case acceptCharset = "accept-charset"
    case action
    case allow
    case allowfullscreen
    case alt
    case `as`
    case `async`
    case autocomplete
    case autoplay
    case blocking
    case charset
    case checked
    case cite
    case closedby
    case cols
    case command
    case commandfor
    case colspan
    case content
    case controls
    case coords
    case crossorigin
    case data
    case datetime
    case decoding
    case dirname
    case alpha
    case colorspace
    case `default`
    case `defer`
    case disabled
    case download
    case enctype
    case fetchpriority
    case `for`
    case form
    case formaction
    case formenctype
    case formmethod
    case formnovalidate
    case formtarget
    case headers
    case height
    case imagesizes
    case imagesrcset
    case color
    case high
    case href
    case hreflang
    case httpEquiv = "http-equiv"
    case integrity
    case ismap
    case kind
    case label
    case list
    case loading
    case loop
    case low
    case max
    case maxlength
    case media
    case method
    case min
    case minlength
    case multiple
    case muted
    case name
    case nomodule
    case novalidate
    case `open`
    case optimum
    case part
    case pattern
    case ping
    case placeholder
    case playsinline
    case popovertarget
    case popovertargetaction
    case poster
    case preload
    case property
    case readonly
    case referrerpolicy
    case rel
    case required
    case reversed
    case rows
    case rowspan
    case sandbox
    case scope
    case selected
    case shadowrootmode
    case shadowrootdelegatesfocus
    case shadowrootclonable
    case shadowrootserializable
    case shadowrootcustomelementregistry
    case shape
    case size
    case sizes
    case span
    case src
    case srcdoc
    case srclang
    case srcset
    case start
    case step
    case target
    case type
    case typemustmatch
    case usemap
    case value
    case width
    case wrap
}
